name: flutter_money_formatter
description: FlutterMoneyFormatter is a Flutter extension to formatting various types of currencies according to the characteristics you like, without having to be tied to any localization.
version: 1.0.0
author: Fadhly Permata <fadhly.permata@gmail.com>
homepage: https://github.com/fadhly-permata/flutter_money_formatter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

flutter:

  plugin:
    androidPackage: com.octapush.moneyformatter.fluttermoneyformatter
    pluginClass: FlutterMoneyFormatterPlugin

